* HANDBOOK

* 1 
** 1.1
  Some things are within our power, while others are not. Within our
  power are opinion, motivation, desire, aversion, and, in a word,
  whatever is of our own doing; not within our power are our body,
  our property, reputation, office, and, in a word, whatever is not of
  our own doing.

** 1.2
   The things that are within our power are by nature free, and immune
   to hindrance and obstruction, while those that are not within our
   power are weak, slavish, subject to hindrance, and not our own.

** 1.3
   Remember, then, that if you regard that which is by nature slavish
   as being free, and that which is not your own as being your own,
   you'll have cause to lament, you'll have a troubled mind, and
   you'll find fault with both gods and human beings; but if you
   regard only that which is your own as being your own, and that
   which isn't your own as not being your own (as is indeed the case),
   no one will ever be able to coerce you, no one will hinder you,
   you'll find fault with no one, you'll accuse no one, you'll do
   nothing whatever against your will, you'll have no enemy, and no
   one will ever harm you because no harm can affect you.

**  1.4
   Since you're aiming, then, at such great things, remember that
   you'll have to exert no small effort to attain them, and that
   you'll have to renounce some things altogether, while postponing
   others for the present.  But if you want to have both these things
   and public office and riches too, you'll quite possibly not even
   gain the latter because you're aiming at the former too, and you'll
   certainly fail to get the former, through which alone happiness and
   freedom can be secured.

** 1.5
   Practise, then, from the very beginning to say to every
   disagreeable impression, "You're an impression and not at all what
   you appear to be."  Then examine it and test it by these rules that
   you possess, and first and foremost by this one, whether the
   impression relates to those things that are within our power, or
   those that aren't within our power; and if it relates to anything
   that isn't within our power, be ready to reply, "That's nothing to
   me.'

* 2
** 2.1
   Remember that desire promises the attaining of what you desire, and
   aversion the avoiding of what you want to avoid, and that he who
   falls into desire is unfortunate, while he who falls into what he
   wants to avoid suffers misforutune.  If you seek to avoid, then,
   only what is contrary to nature among those things that are within
   your own power, you'll never fall into anything that youw ant to
   avoid; but if you wattempt to avoid illness, or death, or poverty,
   you'll suffer misfortune.

** 2.2
   Remove your aversion, then, from everything that is not within our
   power, and transfer it to what is contrary to nature among those
   things that are within our power.  For the present, however,
   suppress your desires entirely; for if you desire any of these
   things that are not within our power, you're bound to be
   unfortunate, while those that are within our power, which it would
   be right for you to desire, aren't yet within your reach.  But use
   only your motives to act or not to act, and even those lightly,
   with reservations and without straining.

* 3
  With regard to everything that is a source of delight to you, or is
  useful to you, or of which you are fond, remember to keep telling
  yourself what kind of thing it is, starting with the most
  insignificant.  If you're fond of a jug, say, "This is a jug that
  I'm fond of," and then, if it gets broken, you won't be upset.  If
  you kiss your child or your wife, say to yourself that it is a human
  being that you're kissing; and then, if one of them should die, you
  won't be upset.

* 4
  When you're about to embark on any action, remind yourself what kind
  of action it is.  If you're going out to take a bath, set before
  your mind the things that hapen at the baths, that people splash
  you, that people knock up against you, that people steal from you.
  And you'll thus undertake the action in a surer manner if you say to
  yourself at the outset, "I want to take a bath and ensure at the
  same time that my choice remains in harmony with nature."  And
  follow the same course in every action that you embark on.  So if
  anything gets in your way while you're taking your bath, you'll be
  ready to tell yourself, "Well, this wasn't the only thing that I
  wanted to do, but I also wanted to keep my choice in harmony with
  nature; and I won't keep it so if I get annoyed at what is
  happening.'

* 5
  It isn't the things themselves that disturb people, but the
  judgments that they form about them.  Death, for instance, is
  nothing terrible, or else it would have seemed so to Socrates too;
  no, it is in the judgment that death is terrible that the terror
  lies.  So accordingly, whenever we're impeded disturbed or
  distressed, we should never blame anyone else, but only ourselves,
  that is to say, our judgments.  It is the act of an ill-educated
  person to cast blame on others when things are going badly for him;
  one who has taken the first step towards becoming properly educated
  casts blame on himself; while one who has taken the first step
  towards becoming properly educated casts blame on himself; while one
  who is fully educated casts blame neither on another nor on himself.

* 6
  Don't pride yourself on any excellence that is not your own.  If a
  horse were to say in its pride, "I'm beautiful," that would be
  bearable; but when you exclaim in your pride, "I have a beautiful
  horse," you should be clear in your mind that you're priding
  yourself on a good quality that belongs to a horse.  What is your
  own, then?  The use of impressions.  So when you're in harmony with
  nature through the right use of impressions, you should then be
  proud of yourself; for then you'll be taking pride in some good of
  your own.

* 7
  When you're on a voyage and your ship has set anchor, if you should
  go ashore to fetch water, you may pick up a little shellfish or bulb
  on the way, but you have to keep your attention directed towards the
  ship, and turn round constantly in case the captain calls you back;
  and if he does, you must cast these things aside, if you don't want
  to be thrown on board trussed up like a sheep.  So in life too, if
  in place of some little bulb or shellfish, a little wife and child
  should be granted to you, there is nothing wrong with that; but if
  the captain calls, you must give up all of these things and run to
  the ship, without even turning around to look back.  And if you're
  an old man, you shouldn't even wander any distance from the ship so
  as not to be missing when the call comes.

* 8
  Don't seek that all that comes about should come about as you wish,
  but wish that everything that comes about should come about just as
  it does, and then you'll have a calm and happy life.

* 9
  Disease is an impediment to the body, but not to choice, unless
  choice wills it to be so.  Lameness is an impediment to the leg, but
  not to choice. And tell yourself the same with regard to everything
  that happens to you, for you'll find that it acts as an impediment
  to something else, but not yourself.
  
* 10
  With regard to everything that happens to you, remember to look
  inside yourself and see what capacity you have to enable you to deal
  with it.  If you catch sight of a beautiful boy or woman, you'll
  find that you have self-control to enable you to deal with that; if
  hard work lies in store for you, you'll find endurance; if
  vilification, you'll find forbearance.  And if you get into the
  habit of following this course, you won't get swept away by your
  impressions.
   
* 11
  Never say about anything, "I've lost it," but rather, "I've given it
  back."  Your child has died?  it has been given back.  Your wife has
  died?  She has been given back.  "My farm has been taken from me.'
  Well, that too has been given back.  "Yes, but the man who took it
  is a rogue."  What does it matter to you through what person the one
  who gave it to you demanded it back?  So long as he entrusts it to
  you, take care of it as something that isn't your own, as travellers
  treat an inn.

* 12
** 12.1
   If you want to make progress, reject such thoughts as these: "If I
   neglect my affairs, I'll have nothing to live on," or, "If I don't
   punish my slave-boy, he'll turn out badly."  For it is better to
   die of hunger, but free from distress and fear, than to live in
   plenty with a troubled mind; and it is better that your slave
   should be bad than that you should be unhappy.  Make a start,
   then, with small things.

**  12.2
   A drop of oil is spilled, a little wine is stolen; say to yourself,
   "Such is the price at which equanimity is bought; such is the price
   that one pays for peace of mind."  For nothing can be acquired at
   no cost at all.  When you summon your slave-boy, keep in mind that
   he may not obey, and even if he does, he may not do what you want;
   but he is hardly so well placed that it depends on him whether
   you're to enjoy peace of mind.

* 13
  If you want to make progress, put up with being thought foolish and
  silly with regard to external things, and don't even wish to give
  the impression of knowing anything about them; and if some people
  come to think that you're somebody of note, regard yourself with
  distrust.  For you should keep your choice in accord with nature
  and, at the same time, hold onto externals, but if you apply your
  attention to oen of those things, you're bound to neglect the other.

* 14
** 14.1
   If you want your children and wife and friends to live for ever,
   you're a fool, because you're wanting things that aren't within
   your power to be within your power, and things that aren't your own
   to be your own.  And like wise, if you want your slave-boy never to
   commit a fault, you're an idiot, because you're wanting badness not
   to be badness, but something else.  If you make it your wish,
   however, not to fail in your desires, that lies within your power.
   So exercise yourself in that which you can achieve.

** 14.2
   Everyone is subject to anyone who has power over what he wants or
   doesn't want, as one who is in a position to confer it or take it
   away.  If anyone wants to be free, then, let him neither want
   anything nor seek to avoid anything that is under the control of
   others; or else he is bound to be a slave.

* 15
  Remember that you should behave in a life as you do at a banquet.
  Something is being passed around and arrives in front of you: reach
  out your hand and take your share politely.  It passes: don't try to
  hold it back.  It has yet to reach you: don't project your desire
  towards it, but wait until it arrives in front of you.  So act
  likewise with regard to your children, to your wife, to public
  office, to riches, and the time will come when you're worthy to have
  a seat at the banquets of the gods.  And if you don't even take
  these things when they're in front of you, but view them with
  contempt, then you'll not only share in the banquets of the gods but
  also in their rule.  For it was by acting in such a way that
  Diogenes, and Heraclitus, and others like them deservedly became
  divine and were called so.
   
* 16
  When you see someone weeping in sorrow because his child has gone
  away, or because he has lost his possessions, take care that you're
  not carried away by the impression that he is indeed in misfortune
  because of these external things, but be ready at once with this
  thought, "It isn't what has happened that so distresses this
  person--for someone else could suffer the same without feeling that
  distress--but rather the judgment that he has formed about it."  As
  far as words go, however, don't hesitate to sympathize with him, or
  even, if the occasion arises, to join in his lamentations; but take
  care that you don't also lament deep inside.

* 17
  Remember that you're an actor in a play, which will be as the author
  chooses, short if he wants it to be short, and long if he wants it
  to be long.  If he wants you to play the part of a beggar, act even
  that part with all your skill; and likewise if you're playing a
  cripple, an official, or a private citizen.  For that is your
  business, to act the role that is assigned to you as well as you
  can; but it is another's part to select that role.

* 18
  When a raven croaks inauspiciously, don't allow yourself to be
  carried away by the impression, but immediately draw a distinction
  within your mind, and say, "None of these omens apply to me, but
  only to my poor body, to my paltry possessions, or my reputation,
  or my children or my wife.  But for me every omen is favourable for
  I want it to be so; for whatever my come about, it is within my
  power to derive benefit from it.'

* 19
** 19.1
   You can be invincible if you never enter a contest in which the
   victory doesn't depend on you.

** 19.2
   So whenever you see someone being preferred above you in the
   awarding of honours, or holding great power, or enjoying high
   repute in any other way, take care that you don't get carried away
   by the outward impression and count him as happy; for if the nature
   of the good is one of the things that lie within our power, there
   can be no place for either envy or jealousy, and you yourself won't
   want to be a praetor or senator or consul, but a free man.  Now
   there is one path alone that leads to that: to despise everything
   that doesn't lie within our own power.

* 20
  Remember that what insults you isn't the person who abuses you or
  hits you, but your judgment that such people are insulting you.  So
  whenever anyone irritates you, recognize that it is your opinion
  that has irritated you.  Try above all, then, not to allow yourself
  to be carried away by the impression; for if you delay things and
  gain time to think, you'll find it easier to gain control of
  yourself.

* 21
  Day by day you must keep before you eyes death and exile and
  everything else that seems frightening, but most especially death;
  and then you'll never harbour any mean thought, nor will you desire
  anything beyond due measure.

* 22
  If you set your desire on pursuing philosophy, prepare from that
  moment to be subject to ridicule, and to have many people mocking
  you, and saying, "Look, he's come back to us having become a
  philosopher all of a sudden!"  and "Where do you suppose he picked
  up that supercilious air?"  You shouldn't assume an air of
  self-importance, but should hold fast to the things that seem best
  to you, as one who has been appointed by God to this post; and
  remember that if you hold true to the same principles, those who
  laughed at you will later come to admire you; but if you allow these
  people to get the better of you, you'll merely be laughed at twice
  over.

* 23
  If it should ever come about that you turn to external things
  because you want to gratify another person, be clear that you've
  lost your plan in life.  Be content, then, to be a philosopher in
  all that you do, and if you also want to be viewed as one, show
  yourself that you are, and you'll be able to achieve that.
  
* 24
** 24.1
   Don't allow these thoughts to upset you: "I'll live unhonoured, and
   be nobody anywhere."  For if it is a bad thing to be unhonoured,
   you cannot be in a bad state as a result of someone else's actions,
   any more than you can be brought into shame in that way.  It is no
   business of yours, surely, to gain a public post or be invited to a
   dinner party?  Certainly not.  So how can this still be a source of
   dishonour?  And how will you be "nobody anywhere" if you only need
   to be somebody in those things that are within your own power, and
   in which it is possible for you to be a man of the highest worth?

** 24.2
   But your friends will be left unhelped?  What do you mean by "left
   unhelped'?  They won't receive any little payouts from you, nor
   will you be able to grant them Roman citizenship.  Well, who told
   you that these are things within our power, rather than being other
   people's business?  And who is able to give to another person
   something that he himself doesn't have?  "Then get hold of some
   money', a friend says, "so that we too may have some.'

** 24.3
   If I can get some while preserving my self-respect,
   trustworthiness, and generosity of mind, show me the way and I'll
   get it; but if you require me to lose the good things that I have
   to enable you to acquire things that aren't good, consider how
   unfair you're being or how foolish.  After all, what would you
   rather have?  Money, or a faithful and self-respecting friend?  So
   help me instead to become such a person, and don't require me to do
   things that would cause me to lose those qualities.

** 24.4
   "But my country', he says, "will receive no help from me, so far as
   I can offer it." Here again, what kind of help do you mean?  It
   won't acquire any arcades or baths through your good offices. And
   what of that?  For it doesn't acquire shoes either through the good
   offices of a blacksmith, or arms through those of a cobbler, it is
   enough that each person fulfils his own function.  And if you
   provide your country with another citizen who is trustworthy and
   self-respecting, would you bring it to no benefit?  "Indeed I
   would." Well then, in that case you wouldn't be of no use to it.
   "What place shall I hold in the state, then?', he asks.  Whatever
   place you can hold while maintaining your trustworthiness and
   self-respect.
   
** 24.5
   But if, out of a wish to help the state, you sacrifice those
   qualities, what use could you be to it, when you've turned out to
   be shameless and untrustworthy?

* 25

** 25.1
   Has someone been honoured above you at a banquet, or in being
   saluted, or in being summoned to give advice? If these things are
   good, you ought to rejoice if someone else has secured them; but if
   they're bad, don't be aggrieved that you haven't secured them.  And
   remember, too, that if you don't resort to the same means as other
   people to acquire things that aren't within our power, you can't
   lay claim to an equal share of them.

** 25.2
   For how can someone who doesn't hang around somebody's door claim
   an equal share with someone who does?  Or if he doesn't join the
   man's retinue when he goes out along with the other person?  Or he
   doesn't sing his praises along with the other person?  You'll be
   unjust, then, and thoroughly greedy, if you refuse to pay the price
   for which these things are marketed, and want to get hold of them
   for nothing.

** 25.3
   Well, at what price are lettuces sold?  An obol perhaps if someone
   pays the obol, then, and gets the lettuces, while you pay nothing
   and get nothing, don't suppose that you're worse off than the man
   who gets the lettuces; for while he has his lettuces, you have your
   obol, which you haven't given away.
   
** 25.4
   Things follow the same course in the present case too.  You haven't
   been invited to somebody's dinner party?  Of course not, because
   you haven't paid the host the price at which he sells the dinner;
   he sells it for praise, he sells it for attention.  Very well,
   then, pay him the price for which it is sold, if it is in your
   interest.  But if you want to make no payment and still receive the
   goods, you're greedy and foolish.  Do you have nothing, then, in
   place of the dinner?  Why, of course you have: you haven't been
   obliged to praise a man whom you didn't want to praise, you didn't
   have to suffer the insolence of the people at the door.
   
* 26
  The will of nature may be learned from those events in life in which
  we don't differ from one another.  For instance, when someone else's
  slave-boy breaks a cup, we're ready at once to say, "That's just one
  of those things."  So you should be clear, then, that if your own
  cup gets broken, you ought to react in exactly the same way as when
  someone else's does.  Transfer the principle to greater matters too.
  Someone else's child or wife has died; there isn't anyone who
  wouldn't say, "Such is our human lot."  And yet when one's own child
  dies, one cries out at once, "Oh poor wretch that I am."  Bug we
  ought to remember how we feel when we hear that the same thing has
  happened to others.

* 27
  Just as a target isn't set up to be missed, so nothing that is bad
  by nature comes into being in the universe.

* 28 
  If someone handed over your body to somebody whom you encountered,
  you'd be furious; but that you hand over your mind to anyone who
  comes along, so that, if he abuses you, it becomes disturbed and
  confused, do you feel no shame at that?

* 29
  discourse 3.15.1-13

  In each action that you understake, consider what comes before and
  what follows after, and only then proceed to the action itself.
  Otherwise you'll set about it with enthusiasm because you've never
  given any thought to the consequences that will follow, and then
  you'll give up in an ignominious fashion when one or another of them
  makes its appearance.
