* HANDBOOK

* 1 
** 1.1
  Some things are within our power, while others are not. Within our
  power are opinion, motivation, desire, aversion, and, in a word,
  whatever is of our own doing; not within our power are our body,
  our property, reputation, office, and, in a word, whatever is not of
  our own doing.

** 1.2
   The things that are within our power are by nature free, and immune
   to hindrance and obstruction, while those that are not within our
   power are weak, slavish, subject to hindrance, and not our own.

** 1.3
   Remember, then, that if you regard that which is by nature slavish
   as being free, and that which is not your own as being your own,
   you'll have cause to lament, you'll have a troubled mind, and
   you'll find fault with both gods and human beings; but if you
   regard only that which is your own as being your own, and that
   which isn't your own as not being your own (as is indeed the case),
   no one will ever be able to coerce you, no one will hinder you,
   you'll find fault with no one, you'll accuse no one, you'll do
   nothing whatever against your will, you'll have no enemy, and no
   one will ever harm you because no harm can affect you.

**  1.4
   Since you're aiming, then, at such great things, remember that
   you'll have to exert no small effort to attain them, and that
   you'll have to renounce some things altogether, while postponing
   others for the present.  But if you want to have both these things
   and public office and riches too, you'll quite possibly not even
   gain the latter because you're aiming at the former too, and you'll
   certainly fail to get the former, through which alone happiness and
   freedom can be secured.

** 1.5
   Practise, then, from the very beginning to say to every
   disagreeable impression, 'You're an impression and not at all what
   you appear to be.'  Then examine it and test it by these rules that
   you possess, and first and foremost by this one, whether the
   impression relates to those things that are within our power, or
   those that aren't within our power; and if it relates to anything
   that isn't within our power, be ready to reply, 'That's nothing to
   me.'

* 2
** 2.1
   Remember that desire promises the attaining of what you desire, and
   aversion the avoiding of what you want to avoid, and that he who
   falls into desire is unfortunate, while he who falls into what he
   wants to avoid suffers misforutune.  If you seek to avoid, then,
   only what is contrary to nature among those things that are within
   your own power, you'll never fall into anything that youw ant to
   avoid; but if you wattempt to avoid illness, or death, or poverty,
   you'll suffer misfortune.

** 2.2
   Remove your aversion, then, from everything that is not within our
   power, and transfer it to what is contrary to nature among those
   things that are within our power.  For the present, however,
   suppress your desires entirely; for if you desire any of these
   things that are not within our power, you're bound to be
   unfortunate, while those that are within our power, which it would
   be right for you to desire, aren't yet within your reach.  But use
   only your motives to act or not to act, and even those lightly,
   with reservations and without straining.

* 3
  With regard to everything that is a source of delight to you, or is
  useful to you, or of which you are fond, remember to keep telling
  yourself what kind of thing it is, starting with the most
  insignificant.  If you're fond of a jug, say, 'This is a jug that
  I'm fond of,' and then, if it gets broken, you won't be upset.  If
  you kiss your child or your wife, say to yourself that it is a human
  being that you're kissing; and then, if one of them should die, you
  won't be upset.

* 4
  When you're about to embark on any action, remind yourself what kind
  of action it is.  If you're going out to take a bath, set before
  your mind the things that hapen at the baths, that people splash
  you, that people knock up against you, that people steal from you.
  And you'll thus undertake the action in a surer manner if you say to
  yourself at the outset, 'I want to take a bath and ensure at the
  same time that my choice remains in harmony with nature.'  And
  follow the same course in every action that you embark on.  So if
  anything gets in your way while you're taking your bath, you'll be
  ready to tell yourself, 'Well, this wasn't the only thing that I
  wanted to do, but I also wanted to keep my choice in harmony with
  nature; and I won't keep it so if I get annoyed at what is
  happening.'

* 5
  It isn't the things themselves that disturb people, but the
  judgments that they form about them.  Death, for instance, is
  nothing terrible, or else it would have seemed so to Socrates too;
  no, it is in the judgment that death is terrible that the terror
  lies.  So accordingly, whenever we're impeded disturbed or
  distressed, we should never blame anyone else, but only ourselves,
  that is to say, our judgments.  It is the act of an ill-educated
  person to cast blame on others when things are going badly for him;
  one who has taken the first step towards becoming properly educated
  casts blame on himself; while one who has taken the first step
  towards becoming properly educated casts blame on himself; while one
  who is fully educated casts blame neither on another nor on himself.

*  6
  Don't pride yourself on any excellence that is not your own.  If a
  horse were to say in its pride, 'I'm beautiful,' that would be
  bearable; but when you exclaim in your pride, 'I have a beautiful
  horse,' you should be clear in your mind that you're priding
  yourself on a good quality that belongs to a horse.  What is your
  own, then?  The use of impressions.  So when you're in harmony with
  nature through the right use of impressions, you should then be
  proud of yourself; for then you'll be taking pride in some good of
  your own.
  
  
   
